name: release

on:
  push:
    tags: [ v*.*.* ]

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v4

      - name: build
        uses: Mutantcat-Working-Group/ChickRemote@builder
        env:
          BUILD_VERSION: ${{ steps.get_version.outputs.VERSION }}

      - name: release
        uses: Mutantcat-Working-Group/ChickRemote@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_VERSION: ${{ steps.get_version.outputs.VERSION }}
